### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by dminca** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#106]
I see last commit was on 26th Dec. '21

**Comment by infa-dsokolov** [comment]
Looks like it is abandoned. The latest nfs provisioner image was release 3 years ago

**Comment by kvaps** [comment]
Currently we have lack of contributors. I do my best to support this project but since I currently don't use it I can't grantee proper care for it.

Thus if someone feels he can take care of it feel free to add yourself into [maintainers list](https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/blob/master/OWNERS)

**Comment by kmova** [comment]
Like @kvaps mentioned we need folks that can maintain this project. If anyone is interested to maintain please come forward. 

With shift of jobs, I am not able to spend time on this project either.
