### ISSUE TITLE
Wanting to maintain this if possible

### ISSUE THREAD

**Issue by aleksasiriski** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#120]
A friendly redditor redirected me to this project and I absolutely love it. My needs are literally Longhorn RWX (NFSv4) without any persistence, and this it exactly that! Now I tried setting this up but the container won't start up with this error:

```
  Normal   Pulling    10s              kubelet            Pulling image "ghcr.io/kubernetes-sigs/nfs-ganesha:v4.0.8"
  Normal   Pulled     5s               kubelet            Successfully pulled image "ghcr.io/kubernetes-sigs/nfs-ganesha:v4.0.8" in 5.3972722s (5.39931032s including waiting)
  Normal   Created    4s (x2 over 5s)  kubelet            Created container nfs-server-provisioner
  Warning  Failed     4s (x2 over 5s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-provisioner=cluster.local/nfs-ganesha-nfs-server-provisioner": stat -provisioner=cluster.local/nfs-ganesha-nfs-server-provisioner: no such file or directory: unknown
  Normal   Pulled     4s               kubelet            Container image "ghcr.io/kubernetes-sigs/nfs-ganesha:v4.0.8" already present on machine
  Warning  BackOff    2s (x2 over 3s)  kubelet            Back-off restarting failed container
  ```
  
I just started learning Go a few days ago and got to like it, so I would like to help fix this if it's code related issue as well as maintain it since I'll be using it, if the devs could point me in the right direction or give me a clue what this error is about I may be able to fix it faster.

**Comment by kvaps** [comment]
Hi, thanks for your interest in helping the project. Currently we have lack of maintainers.

To become part of team you need to perform 3 or more changes, then apply for membership of Kubernetes-SIGs and nfs-ganesha-server-and-external-provisioner in [test-infra](https://github.com/kubernetes/test-infra) project.

more details here:
https://github.com/kubernetes/community/blob/master/community-membership.md

> Now I tried setting this up but the container won't start up with this error

Currently we have a big problem with pipeline for publishing images: see https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/issues/115 for more details.

Possible, you can cooperate with @revant in order to fix that.
Alternatively you can check other [issues](https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/issues) and try to fix them.

**Comment by aleksasiriski** [comment]
Would this be a suitable successor? https://github.com/openebs/dynamic-nfs-provisioner
