### ISSUE TITLE
Extend the disk size of NFS share

### ISSUE THREAD

**Issue by danhul** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#131]
I used helm to deploy nfs-ganesha-provisioner in my k8s cluster. The default size of the NFS share is 124 GB. 
As I add more PVCs using the NFS storage class, the remaining disk space is getting less and less. I would like to extend the size of the actual NFS disk before it gets full. Any idea how that can be done?

**Comment by Shawn1874** [comment]
It doesn't look very promising that you will get a response.  The project has very little documentation stating its purpose, intended goals, or any constraints and limitations of the project.  If using AWS EFS or something like that then it should scale automatically if you have set that up.  Since this project supposedly supports dynamic provisioning, it is unclear how it would interact with a variety of cloud providers.  Perhaps posting examples of your volume claim yaml and a pod spec would help to garner a response.  Also what are you doing for cleanup?  As the SW runs for days, weeks, and/or months is there any type of auto-purging or cleanup being done to recover space?

**Comment by EsDmitrii** [comment]
you need to edit PVC that your statefulset created
in your helm values set 
```
storageClass:
  allowVolumeExpansion: true
```
than:
```
kubectl edit pvc <name> for each PVC in the StatefulSet, to increase its capacity.
kubectl delete sts --cascade=orphan <name> to delete the StatefulSet and leave its pods.
kubectl apply -f <name> to recreate the StatefulSet.
kubectl rollout restart sts <name> to restart the pods, one at a time. During restart, the pod's PVC will be resized.
```

**Comment by khusseini** [comment]
> you need to edit PVC that your statefulset created in your helm values set
> 
> ```
> storageClass:
>   allowVolumeExpansion: true
> ```
> 
> than:
> 
> ```
> kubectl edit pvc <name> for each PVC in the StatefulSet, to increase its capacity.
> kubectl delete sts --cascade=orphan <name> to delete the StatefulSet and leave its pods.
> kubectl apply -f <name> to recreate the StatefulSet.
> kubectl rollout restart sts <name> to restart the pods, one at a time. During restart, the pod's PVC will be resized.
> ```

@EsDmitrii  Would that have an effect on existing PVCs? We have an instance running and disk space is running low. We have PVCs in use with Ganesha and I want to expand the volume, however I don't want to affect running pods. Would they be affected?
