### ISSUE TITLE
Kubernetes YAML manifests not maintained in sync with Helm chart

### ISSUE THREAD

**Issue by consideRatio** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#67]
I note that there is a set of yaml files that i assume to mirror the Helm chart, but they are not updated as work is done on the Helm chart.

Should they be maintained at all, and if so, how should they be maintained? By using `helm template` to generate a rendered set of resources from the Helm charts default values perhaps?

**Comment by afbjorklund** [comment]
They seemed to be working still (like they did before the move*), it was mostly the image location that was outdated...

* ~~https://github.com/kubernetes-retired/nfs-provisioner~~

* ~~https://github.com/kubernetes-retired/external-storage/tree/master/nfs~~

There is also no clear separation in the instructions where the "installation" ends and where the "usage" begins:

* deployment.yaml
* rbac.yaml
* class.yaml
* claim.yaml
* write-pod.yaml

Preferrably there would be an all-in-one, so that one could have an external NFS storage provisioner as a one-liner ?

(my use case is mostly for education and very simple clusters, when trying to move on from HostPath to using PV)

https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#quickstart

**Comment by kvaps** [comment]
/remove-lifecycle rotten

No, those manifests were written manually.

I think the best option would be to have them generated from the helm template command.
We need to add CI job for `/charts/nfs-server-provisioner` to run on every PR and perform:
- Check if chart version bumped
- Check if manifest is generated from the latest chart version

**Comment by consideRatio** [comment]
What about removing them, adding an instruction on how to generate them with helm template into an output dir? It can be a one liner to do so using the --repo flag.

I currently dont see a big enough value for an end user to have these generated in the repo. I imagine they will lead to some confusion, maintenance needs, and additional support questions and complexity.

**Comment by kvaps** [comment]
I suppose someone can continue using them as a library for his jsonnet/kustomize project, but they are definitely not maintained, so such users can just hold on specific commit.

Let's try removing them, if there will be any issues, we can consider the solution later.
