### ISSUE TITLE
Clustering and high availability

### ISSUE THREAD

**Issue by BlaineEXE** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#87]
It's my understanding that the project currently doesn't support creating a highly-available NFS server cluster given the lack of examples on the subject. However, I do also see the `leader-elect` flag on the binary with the description `Start a leader election client and gain leadership before executing the main loop. Enable this when running replicated components for high availability. Default false.`. 

I'm wondering if anyone has used the `leader-elect` in a highly available NFS cluster configuration and what the setup for that looked like.

From an old presentation on NFS-Ganesha [here](https://www.snia.org/sites/default/files/Poornima_NFS_GaneshaForClusteredNAS.pdf), it seems that NFS-Ganesha requires some coordination to handle failover well. I suspect this would be set up manually by any user wanting to use a highly available NFS cluster setup with this provisioner, but I'm not certain.

Going off of the assumption that this project currently can't set up a multiple-NFS-Server cluster that is highly available today, is it within the purview of this project to support such a thing and accept contributions to design and implement the ability to set up a highly-available NFS cluster inside Kubernetes?

@wongma7 @kvaps @kmova

**Comment by kvaps** [comment]
Hi, currently this project intended for use in single replica to export just one PV via FSAL
As far as I know, NFS-ganesha does not support any clustering with the FSAL backend, except, maybe, pNFS, which is still not highly available thus makes no sense for the leader-election feature.

In order to make nfs-server-provisioner highly available you can consider some HA-enabled solution under it eg. Ceph or LINSTOR.
The last one has the fencing implementation via [piraeus-ha-controller](https://github.com/piraeusdatastore/piraeus-ha-controller), which allows you to remove the nfs-server-provisioner from the failed node and reschedule it to another one.

Of course it makes some downtime, but you will have an automation for this at least.
